# Generated by Django 4.0.6 on 2022-07-13 16:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=5)),
                ('location', models.CharField(max_length=50)),
                ('job_type', models.CharField(choices=[('CLT', 'Clt'), ('PJ', 'Pj'), ('TEMPORARY', 'Temporary')], max_length=9)),
                ('regimen_type', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('REMOTE', 'Remote'), ('HYBRID', 'Hybrid')], max_length=10)),
                ('vacancies_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('subscribers_count', models.IntegerField(default=0)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('account', models.ManyToManyField(related_name='accounts_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
