# Generated by Django 4.0.6 on 2022-07-14 14:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='account',
            field=models.ManyToManyField(null=True, related_name='accounts_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
