# Generated by Django 4.0.6 on 2022-07-14 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_company_adress_company_address'),
        ('jobs', '0003_alter_job_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='company_id', to='companies.company'),
            preserve_default=False,
        ),
    ]
