# Generated by Django 4.0.6 on 2022-07-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_skill_options'),
        ('jobs', '0004_job_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(related_name='skill_id', to='skills.skill'),
        ),
    ]
