# Generated by Django 4.0.6 on 2022-07-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_skill_options'),
        ('jobs', '0007_remove_job_subscribers_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(related_name='skills_job', to='skills.skill'),
        ),
    ]
