# Generated by Django 4.0.6 on 2022-07-13 16:10

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_recruiter',
            new_name='is_human_resources',
        ),
    ]
