# Generated by Django 4.0.6 on 2022-07-14 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('accounts', '0003_account_address_account_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.address'),
        ),
    ]
