# Generated by Django 4.0.6 on 2022-07-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_skill_options'),
        ('accounts', '0004_alter_account_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='skills',
            field=models.ManyToManyField(related_name='skills', to='skills.skill'),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Male Transgender', 'Male Transgender'), ('Female Transgender', 'Female Transgender'), ('Non Binary', 'Non Binary'), ('Other', 'Other')], max_length=50),
        ),
    ]
