# Generated by Django 4.0.6 on 2022-07-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_skill_options'),
        ('accounts', '0005_account_skills_alter_account_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='skills',
            field=models.ManyToManyField(related_name='skills_user', to='skills.skill'),
        ),
    ]
