# Generated by Django 4.0.6 on 2022-07-13 16:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=14)),
                ('phone', models.CharField(max_length=11)),
                ('date_joined', models.DateTimeField(auto_now=True)),
                ('adress', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='addresses.address')),
            ],
        ),
    ]
