# Generated by Django 4.0.6 on 2022-07-11 18:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=14)),
                ('phone', models.CharField(max_length=11)),
                ('date_joined', models.DateTimeField(default=datetime.datetime(2022, 7, 11, 18, 13, 51, 879007, tzinfo=utc))),
            ],
        ),
    ]
