# Generated by Django 4.0.6 on 2022-07-13 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='adress',
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.OneToOneField(default=123, on_delete=django.db.models.deletion.CASCADE, to='addresses.address'),
            preserve_default=False,
        ),
    ]
