# Generated by Django 4.0.6 on 2022-07-11 18:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='adress_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 11, 18, 20, 31, 129544, tzinfo=utc)),
        ),
    ]
