# Generated by Django 4.0.6 on 2022-07-20 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_cnpj'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['id']},
        ),
    ]
