# Generated by Django 4.0.6 on 2022-07-14 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['id']},
        ),
    ]
