# Generated by Django 4.0.6 on 2022-07-20 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educations', '0002_alter_education_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['id']},
        ),
    ]
